"""Example external agent for Glasshouse Phase 2.

Demonstrates the full external-agent workflow:

1. Register as an external agent.
2. Poll for an available assignment.
3. Claim a node.
4. Report progress (0.25, 0.5, 0.75).
5. Generate a stub implementation.
6. Submit the implementation with an ``actual_interface``.

Usage:

    python scripts/external_agent_example.py --session-id <id>

This is intentionally trivial — it produces a mock implementation
file. Real external agents (Devin, Cursor, Claude Code, etc.) would
spend most of their time inside step 5 actually generating code.
"""

from __future__ import annotations

import argparse
import sys
import time
from typing import Any, Optional

import requests

DEFAULT_BASE_URL = "http://localhost:8000/api/v1"


def register(base_url: str, name: str, agent_type: str = "custom") -> str:
    """Register the agent and return its id."""
    resp = requests.post(
        f"{base_url}/agents",
        json={"name": name, "type": agent_type},
        timeout=10,
    )
    resp.raise_for_status()
    body = resp.json()
    print(f"[register] agent_id={body['agent_id']} name={name}")
    return body["agent_id"]


def poll_for_assignment(
    base_url: str, session_id: str, agent_id: str
) -> Optional[dict[str, Any]]:
    """Long-poll for an assignment (returns ``None`` when nothing pending)."""
    resp = requests.get(
        f"{base_url}/sessions/{session_id}/assignments",
        params={"agent_id": agent_id},
        timeout=10,
    )
    resp.raise_for_status()
    body = resp.json()
    return body.get("assignment")


def claim_node(
    base_url: str,
    session_id: str,
    node_id: str,
    agent_id: str,
) -> bool:
    """Attempt to claim a node; returns True on success."""
    resp = requests.post(
        f"{base_url}/sessions/{session_id}/nodes/{node_id}/claim",
        json={"agent_id": agent_id},
        timeout=10,
    )
    resp.raise_for_status()
    body = resp.json()
    if body.get("success"):
        node = body.get("node") or {}
        print(f"[claim] {node.get('name', node_id)}")
        return True
    print(f"[claim] failed: {body.get('error')}")
    return False


def report_progress(
    base_url: str,
    session_id: str,
    node_id: str,
    agent_id: str,
    progress: float,
    message: str,
) -> None:
    """Report a progress update for a claimed node."""
    requests.post(
        f"{base_url}/sessions/{session_id}/nodes/{node_id}/status",
        json={
            "agent_id": agent_id,
            "progress": progress,
            "message": message,
        },
        timeout=10,
    )
    print(f"[progress] {progress:.0%} - {message}")


def submit_implementation(
    base_url: str,
    session_id: str,
    node_id: str,
    agent_id: str,
    node_name: str,
) -> None:
    """Submit a stub implementation for the claimed node."""
    actual_interface = {
        "exports": ["main"],
        "imports": [],
        "public_functions": [
            {"name": "main", "signature": "def main() -> None"}
        ],
    }
    safe_name = node_name.replace(" ", "_").lower()
    file_paths = [f"{safe_name}.py"]
    resp = requests.post(
        f"{base_url}/sessions/{session_id}/nodes/{node_id}/implementation",
        json={
            "agent_id": agent_id,
            "file_paths": file_paths,
            "actual_interface": actual_interface,
            "notes": f"Generated by external agent for {node_name}.",
        },
        timeout=10,
    )
    resp.raise_for_status()
    body = resp.json()
    if body.get("success"):
        print(f"[submit] implementation accepted ({len(file_paths)} file(s))")
    else:
        print("[submit] failed!")


def run(
    base_url: str,
    session_id: str,
    name: str,
    agent_type: str,
    poll_interval: float,
) -> None:
    agent_id = register(base_url, name, agent_type)

    while True:
        assignment = poll_for_assignment(base_url, session_id, agent_id)
        if assignment is None:
            print("[poll] no work yet, sleeping…")
            time.sleep(poll_interval)
            continue

        node = assignment["payload"]["node"]
        node_id = node["id"]
        node_name = node["name"]

        if not claim_node(base_url, session_id, node_id, agent_id):
            time.sleep(poll_interval)
            continue

        for progress, msg in [
            (0.25, "Reading node responsibilities"),
            (0.5, "Generating code"),
            (0.75, "Verifying interface"),
        ]:
            report_progress(
                base_url, session_id, node_id, agent_id, progress, msg
            )
            time.sleep(0.4)

        submit_implementation(
            base_url, session_id, node_id, agent_id, node_name
        )

        # Loop again — there may be more nodes available.
        time.sleep(poll_interval)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--session-id", required=True)
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--name", default="example-agent")
    parser.add_argument(
        "--type",
        default="custom",
        choices=["devin", "cursor", "claude", "custom"],
    )
    parser.add_argument(
        "--poll-interval",
        type=float,
        default=1.0,
        help="Seconds between polls when no work is available.",
    )
    args = parser.parse_args()

    try:
        run(
            base_url=args.base_url,
            session_id=args.session_id,
            name=args.name,
            agent_type=args.type,
            poll_interval=args.poll_interval,
        )
    except KeyboardInterrupt:
        print("\n[exit] caught Ctrl-C, shutting down")
        sys.exit(0)


if __name__ == "__main__":
    main()
